package Models.HelpersComunication;

public enum RequestType {
    LOGIN, REGISTRATION,
    FEEDBACK_REQUEST_FRIEND_REQUEST,
    FEEDBACK_SENT_FRIEND_REQUEST,
    SENT_FRIEND_REQUEST,
    RECEIVE_FRIEND_REQUEST,
    ACCEPT_FRIEND,
    JOIN_GROUP,
    LEAVE_GROUP,
    CREATE_GROUP,
    ALERT, MESSAGE,
    FEEDBACK_SIMPLE_RESPONSE,
    GET_GROUPS_REGISTRATION,
    ALERT_USER_CIVIL_PROTECTION,
    ALERT_APP_CIVIL_PROTECTION
}
